FROM alpine:latest

RUN apk add --update --no-cache bash cmake gcc g++ zlib-dev make
# RUN apk add --no-cache gcompat gdb

# optionally add -DCMAKE_BUILD_TYPE=Debug 
RUN --mount=type=bind,source=.,target=/src \
    mkdir -p /build && \
    cd /build && \
    cmake /src && \
    make -j && \
    cp laplace /bin/laplace

# /root is the home directory of the default Docker user
COPY ./adapter/bash/ /root/

WORKDIR /root

ENTRYPOINT ["/bin/laplace", "bash"]